---
name: sponsorblockcast
version: 1.2.3
slug: sponsorblockcast
description: A POSIX shell script that skips sponsored Youtube content on all local
  Chromecasts
url: https://github.com/MrYadro/addon-sponsorblockcast
arch:
- aarch64
- amd64
- armhf
- armv7
- i386
startup: services
options:
  poll_interval: 1
  scan_interval: 300
  categories: sponsor
  youtube_api_key: API_KEY
  debug: false
boot: auto
schema:
  poll_interval: int
  scan_interval: int
  categories: str
  youtube_api_key: str
  debug: bool
host_network: true
